include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true                # 建議用 debugPrint 或 logging 套件
    prefer_const_constructors: true # 優先使用 const 建構子（可提升效能）
    sort_constructors_first: true   # 類別中將建構子放最前
    use_key_in_widget_constructors: true # 自訂 widget 時使用 key
    prefer_final_fields: true       # 優先使用 final
    unnecessary_this: true          # 避免不必要的 this
    prefer_single_quotes: true      # 優先使用單引號
    always_specify_types: true      # 明確寫出變數型別